name:                turtle-service
version:             0.1.0.0
github:              "githubuser/turtle-service"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/turtle-service#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- servant-docs
- servant-swagger
- servant-multipart
- servant-checked-exceptions
- servant-websockets
- aeson
- aeson-casing
- uuid
- text
- postgresql-simple
- bytestring
- http-types
- http-client
- http-client-tls
- http-api-data
- wai
- mtl
- warp
- swagger2
- hspec
- time
- extra
- exceptions
- vector
- websockets

library:
  source-dirs: src

executables:
  turtle-service-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-unused-imports
    dependencies:
    - turtle-service

tests:
  turtle-service-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-unused-imports
    dependencies:
    - turtle-service
